### ISSUE TITLE
About part code of the test class in Train.py

### ISSUE THREAD

**Issue by diaodeyi** [mchong6/GANsNRoses#16]
Thanks for your great work . 
there are some code in the test class :
```
 if i % 2 == 0:
                A2B_mod1 = torch.randn([1, args.latent_dim]).cuda()
                B2A_mod1 = torch.randn([1, args.latent_dim]).cuda()
                A2B_mod2 = torch.randn([1, args.latent_dim]).cuda()
                B2A_mod2 = torch.randn([1, args.latent_dim]).cuda()
```
i  want to konw the meaning of the random sampling.  And why only set these variable when  i % 2 == 0?

**Comment by diaodeyi** [comment]
As for the second question, i mean if i % 2 != 0 , there variable  will not exist, then the program will fault?

**Comment by mchong6** [comment]
I did that so that every two output images will share the same style. So they will have different content but same style. And if i%2 == 0 will be true when i=0, so in the first iteration, the style is defined. Then the next iteration i=1, this code block will not execute and thus, the style will not be updated. There should not be any errors.
